# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'SFLive' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SFLive
  pod 'Kingfisher', '~> 3.1.3'
  pod 'Alamofire', '~> 4.0.1'
  
end
